import fs from 'node:fs';
import path from 'node:path';

const benchmarkPath = path.resolve(__dirname, '../examples/dom-render/benchmark.js');
const benchmarkSource = fs.readFileSync(benchmarkPath, 'utf-8');
const benchmarkHtmlPath = path.resolve(__dirname, '../examples/dom-render/benchmark.html');
const benchmarkHtml = fs.readFileSync(benchmarkHtmlPath, 'utf-8');
const benchmarkCompiledPath = path.resolve(__dirname, '../examples/dom-render/benchmark-compiled.generated.js');
const mainPath = path.resolve(__dirname, '../examples/dom-render/main.js');
const mainSource = fs.readFileSync(mainPath, 'utf-8');
const targetsPath = path.resolve(__dirname, '../examples/dom-render/targets.js');
const targetsSource = fs.readFileSync(targetsPath, 'utf-8');
const runtimePath = path.resolve(__dirname, '../examples/dom-render/lumina-runtime.js');

describe('dom-render live assets', () => {
  test('browser demos use the local runtime asset', () => {
    expect(mainSource).toContain("./lumina-runtime.js");
    expect(targetsSource).toContain("./lumina-runtime.js");
    expect(benchmarkSource).toContain("./lumina-runtime.js");
    expect(fs.existsSync(runtimePath)).toBe(true);
    expect(fs.existsSync(benchmarkCompiledPath)).toBe(true);
  });

  test('benchmark page exposes deeper scenario sections', () => {
    expect(benchmarkHtml).toContain('rel="icon"');
    expect(benchmarkHtml).toContain('export-json');
    expect(benchmarkHtml).toContain('Whole-list patch');
    expect(benchmarkHtml).toContain('Indexed list patch');
    expect(benchmarkHtml).toContain('Stable signal list patch');
    expect(benchmarkHtml).toContain('Initial mount');
    expect(benchmarkHtml).toContain('Keyed reorder');
    expect(benchmarkHtml).toContain('Single keyed move');
    expect(benchmarkHtml).toContain('Complex keyed reorder window');
    expect(benchmarkHtml).toContain('Keyed structure diff');
    expect(benchmarkHtml).toContain('Fine-grained row update');
    expect(benchmarkHtml).toContain('Saved compatible runs: 0');
    expect(benchmarkHtml).toContain('untimed warmup');
    expect(benchmarkHtml).toContain('versioned JSON payload');
    expect(benchmarkHtml).toContain('Benchmark contract');
    expect(benchmarkHtml).toContain('WHATWG DOM');
    expect(benchmarkHtml).toContain('Performance API');
    expect(benchmarkHtml).toContain('Range (ms)');
    expect(benchmarkHtml).toContain('results-whole-list');
    expect(benchmarkHtml).toContain('results-index-list');
    expect(benchmarkHtml).toContain('results-for-list');
    expect(benchmarkHtml).toContain('results-single-move');
    expect(benchmarkHtml).toContain('results-complex-reorder');
    expect(benchmarkHtml).toContain('results-structure-diff');
    expect(benchmarkHtml).toContain('results-fine-grained');
  });

  test('benchmark script runs multiple scenario suites', () => {
    expect(benchmarkSource).toContain('benchmarkLuminaWholeList');
    expect(benchmarkSource).toContain('benchmarkLuminaIndexList');
    expect(benchmarkSource).toContain('benchmarkLuminaCompiledIndexList');
    expect(benchmarkSource).toContain('benchmarkLuminaForList');
    expect(benchmarkSource).toContain('benchmarkLuminaCompiledForList');
    expect(benchmarkSource).toContain('benchmarkLuminaKeyedListReorder');
    expect(benchmarkSource).toContain('benchmarkLuminaCompiledReorder');
    expect(benchmarkSource).toContain('benchmarkLuminaSingleMove');
    expect(benchmarkSource).toContain('benchmarkLuminaKeyedListSingleMove');
    expect(benchmarkSource).toContain('benchmarkLuminaCompiledSingleMove');
    expect(benchmarkSource).toContain('benchmarkLuminaComplexReorder');
    expect(benchmarkSource).toContain('benchmarkLuminaKeyedListComplexReorder');
    expect(benchmarkSource).toContain('benchmarkLuminaCompiledComplexReorder');
    expect(benchmarkSource).toContain('benchmarkLuminaStructureDiff');
    expect(benchmarkSource).toContain('benchmarkLuminaKeyedListStructureDiff');
    expect(benchmarkSource).toContain('benchmarkLuminaCompiledStructureDiff');
    expect(benchmarkSource).toContain('benchmarkVanillaComplexReorder');
    expect(benchmarkSource).toContain('benchmarkVanillaSingleMove');
    expect(benchmarkSource).toContain('benchmarkVanillaStructureDiff');
    expect(benchmarkSource).toContain('benchmarkReactComplexReorder');
    expect(benchmarkSource).toContain('benchmarkReactSingleMove');
    expect(benchmarkSource).toContain('benchmarkReactStructureDiff');
    expect(benchmarkSource).toContain('BENCHMARK_HISTORY_KEY');
    expect(benchmarkSource).toContain('BENCHMARK_MANIFEST');
    expect(benchmarkSource).toContain('BENCHMARK_SCHEMA_VERSION');
    expect(benchmarkSource).toContain('BENCHMARK_SUITE_VERSION');
    expect(benchmarkSource).toContain('BENCHMARK_CONTRACT');
    expect(benchmarkSource).toContain('BENCHMARK_SCENARIO_CONTRACTS');
    expect(benchmarkSource).toContain('BENCHMARK_DOM_SHAPE');
    expect(benchmarkSource).toContain('BENCHMARK_TIMING_CONTRACT');
    expect(benchmarkSource).toContain('SMOKE_MODE');
    expect(benchmarkSource).toContain('LOCAL_ONLY');
    expect(benchmarkSource).toContain('parsePositiveInt');
    expect(benchmarkSource).toContain('MEASURED_RUNS');
    expect(benchmarkSource).toContain('preloadBenchmarkModules');
    expect(benchmarkSource).toContain('bindScenarioSuites');
    expect(benchmarkSource).toContain('unmountWithSmokeSnapshot');
    expect(benchmarkSource).toContain('preserveMountedHostSnapshot');
    expect(benchmarkSource).toContain('Warmup');
    expect(benchmarkSource).toContain('saveBenchmarkRun');
    expect(benchmarkSource).toContain('samplesMs');
    expect(benchmarkSource).toContain('summarizeSamples');
    expect(benchmarkSource).toContain('window.__luminaBenchmarkExport');
    expect(benchmarkSource).toContain('window.__luminaBenchmarkExportJson');
    expect(benchmarkSource).toContain('exportBenchmarkResults');
    expect(benchmarkSource).toContain('createBenchRowDom');
    expect(benchmarkSource).toContain('renderReactBenchRow');
    expect(benchmarkSource).toContain('historyMeta');
    expect(benchmarkSource).toContain('isCompatibleHistoryEntry');
    expect(benchmarkSource).toContain('bench-row');
    expect(benchmarkSource).toContain('window.__luminaBenchmarkResults');
    expect(benchmarkSource).toContain('window.__luminaBenchmarkManifest');
    expect(benchmarkSource).toContain('window.__luminaBenchmarkContract');
    expect(benchmarkSource).toContain('benchmarkReactMemoList');
    expect(benchmarkSource).toContain('benchmarkReactMemoKeyedList');
    expect(benchmarkSource).toContain('benchmarkSolidIndexList');
    expect(benchmarkSource).toContain('benchmarkSolidKeyedIndexList');
    expect(benchmarkSource).toContain('benchmarkLuminaReorder');
    expect(benchmarkSource).toContain('Lumina keyed list');
    expect(benchmarkSource).toContain('benchmarkLuminaFineGrained');
    expect(benchmarkSource).toContain('renderLuminaBenchList');
    expect(benchmarkSource).toContain('luminaRender.indexList');
    expect(benchmarkSource).toContain('luminaRender.forList');
    expect(benchmarkSource).toContain('luminaRender.liveText');
    expect(benchmarkSource).toContain("./benchmark-compiled.generated.js");
    expect(benchmarkSource).toContain('compiledReorder');
    expect(benchmarkSource).toContain("results-mount");
    expect(benchmarkSource).toContain("results-index-list");
    expect(benchmarkSource).toContain("results-for-list");
    expect(benchmarkSource).toContain("results-reorder");
    expect(benchmarkSource).toContain("results-single-move");
    expect(benchmarkSource).toContain("results-complex-reorder");
    expect(benchmarkSource).toContain("results-structure-diff");
  });
});
