(module
  (import "env" "channel_new" (func $channel_new (param i32) (result i32)))
  (import "env" "channel_send" (func $channel_send (param i32 i32) (result i32)))
  (import "env" "channel_close_sender" (func $channel_close_sender (param i32)))
  (import "env" "channel_close_receiver" (func $channel_close_receiver (param i32)))
  (func $capacity_check (result i32)
    (local $id i32)
    (local $first i32)
    (local $second i32)
    (local.set $id (call $channel_new (i32.const 1)))
    (local.set $first (call $channel_send (local.get $id) (i32.const 1)))
    (local.set $second (call $channel_send (local.get $id) (i32.const 2)))
    (call $channel_close_sender (local.get $id))
    (call $channel_close_receiver (local.get $id))
    (i32.add (i32.mul (local.get $first) (i32.const 10)) (local.get $second))
  )
  (export "capacity_check" (func $capacity_check))
)